server:
  port: 8080
  context-path: /

spring:
  #关闭dubbo自动配置
  autoconfigure:
      exclude: \com.alibaba.dubbo.spring.boot.DubboAutoConfiguration,\
               com.alibaba.dubbo.spring.boot.DubboProviderAutoConfiguration,\
               com.alibaba.dubbo.spring.boot.DubboConsumerAutoConfiguration,\
  application:
    name: test-remote
  aop:
    proxy-target-class: true
    auto: true
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: jsp
  test:
    datasource:
      url: jdbc:mysql://118.25.48.224:3306/test?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&amp;noAccessToProcedureBodies=true
      username: wenzq
      password: wenzq123456
      platform: mysql
      initialize: true
      continue-on-error: true
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      maxActive: 10
      initialSize: 5
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  dubbo:
    server: false
    registry:
      address: zookeeper://118.25.48.224:2181
    application:
      id: test-remote
      name: test-remote
    protocol:
      name: dubbo
      port: 20884
      threads: 200
  redis:
    host: 118.25.48.224
    port: 6379
    pass: wenzq123456
    maxIdle: 200
    maxTotal: 600
    maxWaitMillis: 5000
    OnBorrow: true
    testOnReturn: true
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*/*.xml
  typeAliasesPackage: com.wenzq.persistence
  global-config:
    id-type: 0
    db-column-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  level: DEBUG


